Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant"

  # Machine NVA (routeur)
  config.vm.define "nva" do |nva|
    nva.vm.hostname = "nva"
    nva.vm.network "private_network", ip: "192.168.10.2", virtualbox__intnet: "lan"
    nva.vm.network "private_network", ip: "192.168.20.2", virtualbox__intnet: "wan"
    nva.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
    nva.vm.boot_timeout = 300
    nva.vm.provision "shell", path: "provision/nva.sh"
  end

  # Machine Site A (client local)
  config.vm.define "siteA" do |siteA|
    siteA.vm.hostname = "siteA"
    siteA.vm.network "private_network", ip: "192.168.10.3", virtualbox__intnet: "lan"
    siteA.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
    siteA.vm.boot_timeout = 300
    siteA.vm.provision "shell", path: "provision/siteA.sh"
  end

  # Machine Site B (peer VPN)
  config.vm.define "siteB" do |siteB|
    siteB.vm.hostname = "siteB"
    siteB.vm.network "private_network", ip: "192.168.20.3", virtualbox__intnet: "wan"
    siteB.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"
    siteB.vm.boot_timeout = 300
    siteB.vm.provision "shell", path: "provision/siteB.sh"
  end

  # Monitoring (Prometheus + Grafana)
config.vm.define "monitoring" do |monitoring|
  monitoring.vm.hostname = "monitoring"
  monitoring.vm.network "private_network", ip: "192.168.10.4", virtualbox__intnet: "lan"
  monitoring.vm.network "forwarded_port", guest: 22, host: 2204, id: "ssh"
  
  # 👉 Redirection des ports web vers l’hôte
  monitoring.vm.network "forwarded_port", guest: 9090, host: 9090  # Prometheus
  monitoring.vm.network "forwarded_port", guest: 3000, host: 3000  # Grafana
  
  monitoring.vm.boot_timeout = 300
  monitoring.vm.provision "shell", path: "provision/monitoring.sh"
end

end
